apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: meu-primeiro-app-set
  namespace: argocd
spec:
  goTemplate: true # Como isso está TRUE, as variáveis precisam de um PONTO .
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/JessicaApBueno/descomplicando-gitops-no-kubernetes-argocd.git
        revision: feat/day3
        directories:
          - path: applicationset/apps/*
  template:
    metadata:
      name: '{{.path.basename}}' # Adicionado o PONTO
    spec:
      project: default
      source:
        repoURL: https://github.com/JessicaApBueno/descomplicando-gitops-no-kubernetes-argocd.git
        targetRevision: feat/day3
        path: '{{.path}}' # Adicionado o PONTO
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}' # Adicionado o PONTO
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true